[versions]
paperweight-userdev = "2.0.0-beta.18"
run-paper = "3.0.0"
shadow = "9.2.2"
paper = "1.21.8-R0.1-SNAPSHOT"
classgraph = "4.8.181"
java = "21"

[plugins]
paperweight-userdev = { id = "io.papermc.paperweight.userdev", version.ref = "paperweight-userdev" }
run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "run-paper" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }

[libraries]
classgraph = { group = "io.github.classgraph", name = "classgraph", version.ref = "classgraph" }